server:
  port: 7911

spring:
  application:
    name: microservice-movie
#  zipkin:
#    base-url: http://localhost:8750
#  sleuth:
#    sampler:
#      probability: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8720/eureka/

