server:
  port: 8760

spring:
  application:
    name: common-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


zuul:
#  prefix: /api
  routes:
    microservice-user:
      path: /contidion/self
      serviceId: microservice-user