
server:
  port: 7931

spring:
  application:
    name: microservice-secskill
#  zipkin:
#    base-url: http://localhost:8750
#  sleuth:
#    sampler:
#      probability: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

