
server:
  port: 7901

spring:
  application:
    name: microservice-admin
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
#  zipkin:
#    base-url: http://localhost:8750
#  sleuth:
#    sampler:
#      probability: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


