
server:
  port: 7921

spring:
  application:
    name: microservice-order
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    connection-timeout: 2000ms
    publisher-confirms: true  #生产者确认消息  confirmListener
    publisher-returns: true   #消息未被消费则原封不动返回，不被处理  returnListener
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3


#  zipkin:
#    base-url: http://localhost:8750
#  sleuth:
#    sampler:
#      probability: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


